services:
  - type: web
    name: smart-attendance
    runtime: docker
    plan: free
    healthCheckPath: /up
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: DB_CONNECTION
        value: pgsql
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: MAIL_MAILER
        value: log
      - key: MAIL_FROM_NAME
        value: Smart Attendance
      - key: MAIL_FROM_ADDRESS
        sync: false
